export const TRANSACTION_KEYWORD_ACTION_TYPES = {
  SET_INCOME_TRANSACTION_KEYWORD_LIST: "transactionKeyword/SET_INCOME_TRANSACTION_KEYWORD_LIST",
  SET_EXPENDITURE_TRANSACTION_KEYWORD_LIST: "transactionKeyword/SET_EXPENDITURE_TRANSACTION_KEYWORD_LIST",
}